// Inlined from AXe (cameroncooke/AXe) — MIT License
import Foundation

struct KeyEvent {
  let keyCode: Int
  let shift: Bool
}

extension KeyEvent {
  static func keyCodeForString(_ string: String) -> KeyEvent {
    guard let character = string.first, string.count == 1 else { return KeyEvent(keyCode: 0, shift: false) }

    switch String(character) {
    case "a": return KeyEvent(keyCode: 4, shift: false)
    case "b": return KeyEvent(keyCode: 5, shift: false)
    case "c": return KeyEvent(keyCode: 6, shift: false)
    case "d": return KeyEvent(keyCode: 7, shift: false)
    case "e": return KeyEvent(keyCode: 8, shift: false)
    case "f": return KeyEvent(keyCode: 9, shift: false)
    case "g": return KeyEvent(keyCode: 10, shift: false)
    case "h": return KeyEvent(keyCode: 11, shift: false)
    case "i": return KeyEvent(keyCode: 12, shift: false)
    case "j": return KeyEvent(keyCode: 13, shift: false)
    case "k": return KeyEvent(keyCode: 14, shift: false)
    case "l": return KeyEvent(keyCode: 15, shift: false)
    case "m": return KeyEvent(keyCode: 16, shift: false)
    case "n": return KeyEvent(keyCode: 17, shift: false)
    case "o": return KeyEvent(keyCode: 18, shift: false)
    case "p": return KeyEvent(keyCode: 19, shift: false)
    case "q": return KeyEvent(keyCode: 20, shift: false)
    case "r": return KeyEvent(keyCode: 21, shift: false)
    case "s": return KeyEvent(keyCode: 22, shift: false)
    case "t": return KeyEvent(keyCode: 23, shift: false)
    case "u": return KeyEvent(keyCode: 24, shift: false)
    case "v": return KeyEvent(keyCode: 25, shift: false)
    case "w": return KeyEvent(keyCode: 26, shift: false)
    case "x": return KeyEvent(keyCode: 27, shift: false)
    case "y": return KeyEvent(keyCode: 28, shift: false)
    case "z": return KeyEvent(keyCode: 29, shift: false)
    case "A": return KeyEvent(keyCode: 4, shift: true)
    case "B": return KeyEvent(keyCode: 5, shift: true)
    case "C": return KeyEvent(keyCode: 6, shift: true)
    case "D": return KeyEvent(keyCode: 7, shift: true)
    case "E": return KeyEvent(keyCode: 8, shift: true)
    case "F": return KeyEvent(keyCode: 9, shift: true)
    case "G": return KeyEvent(keyCode: 10, shift: true)
    case "H": return KeyEvent(keyCode: 11, shift: true)
    case "I": return KeyEvent(keyCode: 12, shift: true)
    case "J": return KeyEvent(keyCode: 13, shift: true)
    case "K": return KeyEvent(keyCode: 14, shift: true)
    case "L": return KeyEvent(keyCode: 15, shift: true)
    case "M": return KeyEvent(keyCode: 16, shift: true)
    case "N": return KeyEvent(keyCode: 17, shift: true)
    case "O": return KeyEvent(keyCode: 18, shift: true)
    case "P": return KeyEvent(keyCode: 19, shift: true)
    case "Q": return KeyEvent(keyCode: 20, shift: true)
    case "R": return KeyEvent(keyCode: 21, shift: true)
    case "S": return KeyEvent(keyCode: 22, shift: true)
    case "T": return KeyEvent(keyCode: 23, shift: true)
    case "U": return KeyEvent(keyCode: 24, shift: true)
    case "V": return KeyEvent(keyCode: 25, shift: true)
    case "W": return KeyEvent(keyCode: 26, shift: true)
    case "X": return KeyEvent(keyCode: 27, shift: true)
    case "Y": return KeyEvent(keyCode: 28, shift: true)
    case "Z": return KeyEvent(keyCode: 29, shift: true)
    case "1": return KeyEvent(keyCode: 30, shift: false)
    case "2": return KeyEvent(keyCode: 31, shift: false)
    case "3": return KeyEvent(keyCode: 32, shift: false)
    case "4": return KeyEvent(keyCode: 33, shift: false)
    case "5": return KeyEvent(keyCode: 34, shift: false)
    case "6": return KeyEvent(keyCode: 35, shift: false)
    case "7": return KeyEvent(keyCode: 36, shift: false)
    case "8": return KeyEvent(keyCode: 37, shift: false)
    case "9": return KeyEvent(keyCode: 38, shift: false)
    case "0": return KeyEvent(keyCode: 39, shift: false)
    case "\n": return KeyEvent(keyCode: 40, shift: false)
    case ";": return KeyEvent(keyCode: 51, shift: false)
    case "=": return KeyEvent(keyCode: 46, shift: false)
    case ",": return KeyEvent(keyCode: 54, shift: false)
    case "-": return KeyEvent(keyCode: 45, shift: false)
    case ".": return KeyEvent(keyCode: 55, shift: false)
    case "/": return KeyEvent(keyCode: 56, shift: false)
    case "`": return KeyEvent(keyCode: 53, shift: false)
    case "[": return KeyEvent(keyCode: 47, shift: false)
    case "\\": return KeyEvent(keyCode: 49, shift: false)
    case "]": return KeyEvent(keyCode: 48, shift: false)
    case "'": return KeyEvent(keyCode: 52, shift: false)
    case " ": return KeyEvent(keyCode: 44, shift: false)
    case "!": return KeyEvent(keyCode: 30, shift: true)
    case "@": return KeyEvent(keyCode: 31, shift: true)
    case "#": return KeyEvent(keyCode: 32, shift: true)
    case "$": return KeyEvent(keyCode: 33, shift: true)
    case "%": return KeyEvent(keyCode: 34, shift: true)
    case "^": return KeyEvent(keyCode: 35, shift: true)
    case "&": return KeyEvent(keyCode: 36, shift: true)
    case "*": return KeyEvent(keyCode: 37, shift: true)
    case "(": return KeyEvent(keyCode: 38, shift: true)
    case ")": return KeyEvent(keyCode: 39, shift: true)
    case "_": return KeyEvent(keyCode: 45, shift: true)
    case "+": return KeyEvent(keyCode: 46, shift: true)
    case "{": return KeyEvent(keyCode: 47, shift: true)
    case "}": return KeyEvent(keyCode: 48, shift: true)
    case ":": return KeyEvent(keyCode: 51, shift: true)
    case "\"": return KeyEvent(keyCode: 52, shift: true)
    case "|": return KeyEvent(keyCode: 49, shift: true)
    case "<": return KeyEvent(keyCode: 54, shift: true)
    case ">": return KeyEvent(keyCode: 55, shift: true)
    case "?": return KeyEvent(keyCode: 56, shift: true)
    case "~": return KeyEvent(keyCode: 53, shift: true)
    default: return KeyEvent(keyCode: 0, shift: false)
    }
  }
}
